name: CI - Build & Push to ECR

on:
  workflow_run:
    workflows: ["Terraform - Infrastructure"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ahmad-strapi-bluegreen

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        id: set-tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}

          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_URI:${GITHUB_SHA} \
            -t $ECR_URI:latest \
            -f my-strapi-app/Dockerfile \
            my-strapi-app \
            --push